// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHJIW5v0K_rwN7AgJH4BTBagY2b-DI2c',
    appId: '1:740607827067:web:3cc3f3841078a12c6a16de',
    messagingSenderId: '740607827067',
    projectId: 'auth-d3113',
    authDomain: 'auth-d3113.firebaseapp.com',
    storageBucket: 'auth-d3113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xsSzh0MxlyT_5u9mZ6_ZprV_JzZ44QY',
    appId: '1:740607827067:android:fc05ab9ceaf053f86a16de',
    messagingSenderId: '740607827067',
    projectId: 'auth-d3113',
    storageBucket: 'auth-d3113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulXag-HVeZCZnHGAfrIdfguoHnysouQI',
    appId: '1:740607827067:ios:567e56e62e20ab046a16de',
    messagingSenderId: '740607827067',
    projectId: 'auth-d3113',
    storageBucket: 'auth-d3113.firebasestorage.app',
    iosBundleId: 'com.example.loginPage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBulXag-HVeZCZnHGAfrIdfguoHnysouQI',
    appId: '1:740607827067:ios:567e56e62e20ab046a16de',
    messagingSenderId: '740607827067',
    projectId: 'auth-d3113',
    storageBucket: 'auth-d3113.firebasestorage.app',
    iosBundleId: 'com.example.loginPage1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGHJIW5v0K_rwN7AgJH4BTBagY2b-DI2c',
    appId: '1:740607827067:web:41a7342a6bb32c0b6a16de',
    messagingSenderId: '740607827067',
    projectId: 'auth-d3113',
    authDomain: 'auth-d3113.firebaseapp.com',
    storageBucket: 'auth-d3113.firebasestorage.app',
  );
}
